reusable

diff --git a/.github/workflows/deploy-template.yml b/.github/workflows/deploy-template.yml
--- a/.github/workflows/deploy-template.yml
+++ b/.github/workflows/deploy-template.yml
@@ -53,9 +53,8 @@ jobs:
 
             # Download the artifact directly on EC2
             echo "Downloading artifact from JFrog..."
-            jfrog rt download "my-repo/libs-release-local/*.jar" /home/ubuntu/ || echo "Artifact download failed"
+            jfrog rt download "artifactory-repo/libs-release-local/*.jar" /home/ubuntu/ || echo "Artifact download failed"
             
             # Run the Spring Boot application
             echo "Running the Spring Boot application..."
             nohup java -jar /home/ubuntu/libs-release-local/springboot-test-0.0.1-SNAPSHOT.jar &
-            
